### PR TITLE
Callback assign syn::Path

### PR DESCRIPTION
**Pull request by maciejhirsz**
Switched derive macro to using `bae`, makes code a lot of simpler and makes it easy to do `#[ramhorns(callback = foo::bar)]`. Updated dependencies. CC @grego.

### CODE REVIEW

**Comment by grego** [comment]
Very nice! LGTM

**Comment by maciejhirsz** [comment]
Release 0.13 done :)

**Comment by grego** [comment]
That's great.
FYI, based on your past work on Ramhorns, I put together a preprocessor for `pulldown_cmark` that highlights syntax, which can be used as a callback: [cmark-syntax](https://github.com/grego/cmark-syntax)

**Comment by maciejhirsz** [comment]
@grego nice! :D

**Pull request merged**
