### PR TITLE
feat: add rename_all and index-based sections

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Hey @maciejhirsz, thanks for this awesome lib! I've been using it for some little project I'm working on. I had to add a few things so far, like rename_all and index based sections.
Would you be interested in merging these? If so I can tidy up and make any changes etc
Thanks!

### CODE REVIEW

**Comment by maciejhirsz** [comment]
@tiagolobocastro sorry for being late to the party here.

Not a big fan of index based sections, I wouldn't mind having them if they didn't imply performance drop for everything, regardless of whether you're using them or not. I reckon this is something that should be handled by the data you feed into the template rather than the template itself.

`rename_all` on the other hand looks like a really good feature, would gladly accept that part of the PR!

**Comment by maciejhirsz** [comment]
> Is there any benchmark we can use to see if this makes a difference?

The standard benchmark should be sufficient. I'm not so worried about the derive macro - I'm generally okay putting more complexity there for features / runtime performance. I'm just overly pedantic and stuff I worry about is this:

https://github.com/maciejhirsz/ramhorns/blob/db7c14b3852e6e7a05844264db0bf211a1679eaf/ramhorns/src/content.rs#L382-L397

It only affects `Vec`s, though it should probably be also done for slices. Anyhow, if we can figure out how to do this without an extra branch on render, by whatever combination of derive magic + template parsing step, I'd feel much better about it.

**Comment by tiagolobocastro** [comment]
Hey, sorry for delay, I started working on my project again and remembered this.

A guess a dirty way around this would be to use features?
Another approach would be to control this at render time base on some options part of the render call or perhaps a certain trait being implemented?

**Comment by maciejhirsz** [comment]
@tiagolobocastro If you do it behind a feature flag I'd gladly merge the PR as-is. It is, as you say, a dirty way of doing it, but it checks my checklist, and it will give me something to tinker on to see if I can make it proper zero-cost (for the "if you don't use it you don't pay for it" part of zero-cost) in the future.

**Comment by tiagolobocastro** [comment]
Cool, I will try to tidy up the code, add a few more tests (plus fix the GHA tests) and I'll mark this as ready when appropriate. Thanks!

**Comment by tiagolobocastro** [comment]
Hey @maciejhirsz, better late than never, I hope 😅
I've added a feature for index-based as suggested and left rename as it was, please take a look whenever you get a chance, thanks!

**Comment by maciejhirsz** [comment]
@tiagolobocastro better late than never to merge too I hope :upside_down_face:

**Comment by tiagolobocastro** [comment]
Awesome, thank you!

**Comment by maciejhirsz** [comment]
Finally released with 1.0.

**Pull request merged**
