### PR TITLE
Relicense under MPL-2.0

### LINKED ISSUE #66: LGPL license?
Context: There is a PR for the paperclip crate (https://github.com/paperclip-rs/paperclip/pull/506) that introduces openAPI v3 spec + moustache templates and adds ramhorns as a dependency for processing said templates. However, since ramhorns is under GPL v3 and the paperclip crate is licensed under MIT then merging this would require changing the entire crate's license to GPL v3, which is something that the author (understandably) doesn't want to do. In that case relicensing ramhorns under LGPL v3 would allow it to be included there (while retaining most of the benefits of GPL v3 license)

Is it something that's feasible?

### PR DESCRIPTION
**Pull request by maciejhirsz**
Closes #66.

Outstanding contributors that need to agree:

+ [x] @htrefil for #14.
+ [x] @creativcoder for #39.

#14 is probably not necessary since that PR I've rewritten myself, #39 might not be necessary since there isn't really any other way to do that PR and it doesn't contribute any business logic but I'd rather be safe than sorry.

### CODE REVIEW

**Comment by halvko** [comment]
Sorry I wasn’t clear enough, I accept the relicensing

**Comment by maciejhirsz** [comment]
> Sorry I wasn’t clear enough, I accept the relicensing

Oh sorry, and sorry for the ping! I got the wrong person and PR :facepalm:

**Comment by htrefil** [comment]
Fine by me.

**Comment by creativcoder** [comment]
Works for me

**Pull request merged**
